### ISSUE TITLE
ws error on linux with node v0.10.25

### ISSUE THREAD

**Issue by pjump** [nitoyon/livereloadx#22]
On Linux, I got this beautiful error when my file updated:

015-03-12 12:22:32 - info:  Config:
2015-03-12 12:22:32 - info:    - mode:   static
2015-03-12 12:22:32 - info:    - port:   8000
2015-03-12 12:22:32 - info:    - filter:
2015-03-12 12:22:32 - info:      1: exclude ".{git,svn}/"
2015-03-12 12:22:32 - info:      2: include "*/"
2015-03-12 12:22:32 - info:      3: include "*.{html,shtml,tmpl,xml,css,js,json,jpeg,jpg,gif,png,ico,cgi,php,py,pl,pm,rb}"
2015-03-12 12:22:32 - info:      4: exclude "*"
2015-03-12 12:22:32 - info:  Enabled static mode.
2015-03-12 12:22:32 - info:  Waiting on port 8000...
2015-03-12 12:22:32 - info:  Watching "/home/pskocik/dev/attach_function"...
2015-03-12 12:22:34 - info:  127.0.0.1 - "GET /README.html HTTP/1.1" 200 4379
2015-03-12 12:22:34 - info:  127.0.0.1 - "GET /livereload.js?snipver=2&port=8000 HTTP/1.1" 200 33591
2015-03-12 12:22:34 - info:  127.0.0.1 - new connection to websocket server
/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/Receiver.js:268
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                              ^
TypeError: Cannot call method 'unmask' of undefined
    at Receiver.unmask (/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/Receiver.js:268:47)
    at Receiver.opcodes.1.finish (/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/Receiver.js:383:25)
    at Receiver.expectHandler (/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/home/pskocik/.node/lib/node_modules/livereloadx/node_modules/ws/lib/WebSocket.js:663:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

**Comment by pjump** [comment]
This is a problem in the old version of ws that livereloadx is curently using.
