### ISSUE TITLE
Consider upgrading 'ws' module dependency

### ISSUE THREAD

**Issue by vmadman** [nitoyon/livereloadx#33]
Hi, I am getting an uncaught error in my application, which implements LiveReloadX programmatically.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: zlib binding closed
    at DeflateRaw.Zlib._transform (zlib.js:499:15)
    at DeflateRaw.Transform._read (_stream_transform.js:167:10)
    at DeflateRaw.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)
```

This error is hard to pin down, precisely, so I cannot definitely say that LiveReloadX is part of the problem, but I _strongly_ suspect that it is because it implements `ws`, which has this **[issue](https://github.com/websockets/ws/issues/628)** and this **[pull request](https://github.com/websockets/ws/pull/632)** (which supposedly fixed the problem, as of `ws@1.0.0`).

Since `ws` is now at version `2.2.2`, would you please consider upgrading your dependency?

Thanks,

**Comment by elsassph** [comment]
I updated `ws` to latest in PR #36 if you want to try - not sure this project is still maintained unfortunately. Maybe it should be forked...

**Comment by elsassph** [comment]
@nitoyon would be nice to release the recent changes?

**Comment by nitoyon** [comment]
@elsassph 0.3.10 has been released 🎉 
Thank you for your contribution 😃
