### ISSUE TITLE
Server crash regression

### ISSUE THREAD

**Issue by elsassph** [nitoyon/livereloadx#37]
With master branch, every 2nd executions the server crashes on the 1st request with:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
```

**Comment by nitoyon** [comment]
It seems the regression  caused by #37. Can you fix it?

**Comment by elsassph** [comment]
Fixed in PR
