### ISSUE TITLE
Crashing on Windows

### ISSUE THREAD

**Issue by juresrpcic** [nitoyon/livereloadx#5]
Occasionally LiveReloadX will crash - it always gives the same error message

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch EPERM
    at errnoException (fs.js:1019:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1037:26)
```

Regular LiveReload crashed more often and this crash usually happens when I have multiple tabs open in Chrome and switching heavily. Is it possible to fix it? Maybe at least relaunch LiveReloadX when this happens - otherwise I have to exit from command prompt and run it again (using a shortcut).

**Comment by elsassph** [comment]
I have this error when running without delay - adding `-d 10` for instance fixes it for me.
